--- #YAML:1.0
name:               MojoX-Ping
version:            0.3
abstract:           ~
author:
    - Sergey Zasenko <d3fin3@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::Poll:     0
    Mojolicious:  0.999942
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
