---
abstract: 'asynchronous ping with L<Mojolicious> (DEPRECATED).'
author:
  - 'Sergey Zasenko <d3fin3@gmail.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120351'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MojoX-Ping
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: 2.37
resources:
  repository: https://github.com/und3f/mojox-ping
version: 0.511
